### ISSUE TITLE
Move into the alexa-js organization?

### ISSUE THREAD

**Issue by dblock** [rzane/alexa-home-server#1]
Would you like to move this repo into the newly created alexa-js organization, https://github.com/alexa-js? 

This would reduce bus factor as currently only @rzane can add contributors to this project. By moving org admins can at least add new people, currently that's @matt-kruse and myself.

If you do want to do this, because Github requires one be admin of both source and destination, transfer the repo to me (@dblock) and I'll immediately move it to the org.

**Comment by rzane** [comment]
Sure, I'd be okay with that.

**Comment by dblock** [comment]
@rzane See above, transfer to me and I'll immediately move it into the org.

**Comment by rzane** [comment]
💥 done

**Comment by dblock** [comment]
And here we are. Feel free to add me to npm as well.

**Comment by rzane** [comment]
Sure, I've added you to NPM.
